=== yoiang/Rittai-Picross/Puzzle.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://Rittai.Picross"
    elementFormDefault="qualified" xmlns:tns="http://Rittai.Picross">
    <xsd:element name="Puzzle">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="PaintColor" type="tns:Color" minOccurs="0"/>
                <xsd:element name="Cubes">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Cube" maxOccurs="unbounded" type="tns:Cube"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="BackgroundColor" type="tns:Color" minOccurs="0"/>
            </xsd:sequence>
            <xsd:attribute name="Title" type="xsd:string"/>
            <xsd:attribute name="XSize" type="xsd:integer" use="required"/>
            <xsd:attribute name="YSize" type="xsd:integer" use="required"/>
            <xsd:attribute name="ZSize" type="xsd:integer" use="required"/>
            <xsd:attribute name="AllowedFails" type="xsd:integer" use="required"/>
            <xsd:attribute name="Version" type="xsd:integer" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="Cube">
        <xsd:sequence>
            <xsd:element name="FinishedColor" type="tns:Color"/>
        </xsd:sequence>
        <xsd:attribute name="Solid" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:complexType name="Color">
        <xsd:sequence>
            <xsd:element name="r" type="xsd:float" default="0.0"/>
            <xsd:element name="g" type="xsd:float" default="0.0"/>
            <xsd:element name="b" type="xsd:float" default="0.0"/>
            <xsd:element name="a" default="0.0" type="xsd:float"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Vector3i">
        <xsd:sequence>
            <xsd:element name="x" type="xsd:integer"/>
            <xsd:element name="y" type="xsd:integer"/>
            <xsd:element name="z" type="xsd:integer"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== yoiang/Rittai-Picross/puzzles/Debug/Test.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Test.xml
    Created on : September 8, 2009, 12:15 AM
    Author     : Ian
    Description:
        Purpose of the document follows.
-->

<ns1:Puzzle  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns1='http://Rittai.Picross'
   xsi:schemaLocation='http://Rittai.Picross file:/Users/Ian/workspace/Personal/Netbeans/Rittai%20Picross/src/js/Puzzle.xsd' 
   Title="Test.xml" XSize="2" YSize="2" ZSize="2" AllowedFails="2" Version="3">

    <ns1:PaintColor>
        <ns1:r>0</ns1:r>
        <ns1:g>0</ns1:g>
        <ns1:b>1</ns1:b>
        <ns1:a>1</ns1:a>
    </ns1:PaintColor>
    <ns1:Cubes>
        <ns1:Cube Solid="false">
            <ns1:FinishedColor>
                <ns1:r>0.0</ns1:r>
                <ns1:g>0.0</ns1:g>
                <ns1:b>0.0</ns1:b>
                <ns1:a>1.0</ns1:a>
            </ns1:FinishedColor>
        </ns1:Cube>
        <ns1:Cube Solid="true">
            <ns1:FinishedColor>
                <ns1:r>1.0</ns1:r>
                <ns1:g>0.0</ns1:g>
                <ns1:b>0.0</ns1:b>
                <ns1:a>1.0</ns1:a>
            </ns1:FinishedColor>
        </ns1:Cube>
        <ns1:Cube Solid="false">
            <ns1:FinishedColor>
                <ns1:r>0.0</ns1:r>
                <ns1:g>1.0</ns1:g>
                <ns1:b>0.0</ns1:b>
                <ns1:a>1.0</ns1:a>
            </ns1:FinishedColor>
        </ns1:Cube>
        <ns1:Cube Solid="false">
            <ns1:FinishedColor>
                <ns1:r>0.0</ns1:r>
                <ns1:g>0.0</ns1:g>
                <ns1:b>1.0</ns1:b>
                <ns1:a>1.0</ns1:a>
            </ns1:FinishedColor>
        </ns1:Cube>

        <ns1:Cube Solid="true">
            <ns1:FinishedColor>
                <ns1:r>1.0</ns1:r>
                <ns1:g>1.0</ns1:g>
                <ns1:b>0.0</ns1:b>
                <ns1:a>1.0</ns1:a>
            </ns1:FinishedColor>
        </ns1:Cube>
        <ns1:Cube Solid="true">
            <ns1:FinishedColor>
                <ns1:r>1.0</ns1:r>
                <ns1:g>0.0</ns1:g>
                <ns1:b>1.0</ns1:b>
                <ns1:a>1.0</ns1:a>
            </ns1:FinishedColor>
        </ns1:Cube>
        <ns1:Cube Solid="true">
            <ns1:FinishedColor>
                <ns1:r>0.0</ns1:r>
                <ns1:g>1.0</ns1:g>
                <ns1:b>1.0</ns1:b>
                <ns1:a>1.0</ns1:a>
            </ns1:FinishedColor>
        </ns1:Cube>
        <ns1:Cube Solid="true">
            <ns1:FinishedColor>
                <ns1:r>1.0</ns1:r>
                <ns1:g>1.0</ns1:g>
                <ns1:b>1.0</ns1:b>
                <ns1:a>1.0</ns1:a>
            </ns1:FinishedColor>
        </ns1:Cube>
    </ns1:Cubes>

</ns1:Puzzle>

=== yoiang/Rittai-Picross/puzzles/Tutorial/2 - Break a Block, Save a Block.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:Puzzle Version="3" Title="" XSize="1" YSize="1" ZSize="2" AllowedFails="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://Rittai.Picross" xsi:schemaLocation="http://Rittai.Picross file:/Users/Ian/workspace/Personal/Netbeans/Rittai%20Picross/src/js/Puzzle.xsd">
    <ns1:PaintColor>
        <ns1:r>0</ns1:r>
        <ns1:g>0</ns1:g>
        <ns1:b>1</ns1:b>
        <ns1:a>1</ns1:a>
    </ns1:PaintColor>
    <ns1:Cubes>
        <ns1:Cube Solid="false">
            <ns1:FinishedColor>
                <ns1:r>1</ns1:r>
                <ns1:g>1</ns1:g>
                <ns1:b>1</ns1:b>
                <ns1:a>1</ns1:a>
            </ns1:FinishedColor>
        </ns1:Cube>
        <ns1:Cube Solid="true">
            <ns1:FinishedColor>
                <ns1:r>1</ns1:r>
                <ns1:g>1</ns1:g>
                <ns1:b>1</ns1:b>
                <ns1:a>1</ns1:a>
            </ns1:FinishedColor>
        </ns1:Cube>
    </ns1:Cubes>
</ns1:Puzzle>
